" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"
"  If you don't understand a setting in here, just type :h 'setting'.

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Second, init vim-pathogen
call pathogen#infect()


" Switch syntax highlighting on.
syntax on

" Enable file type detection, plugin and language-dependent indenting.
filetype plugin indent on

if has("gui_running")
    " color scheme define 
    silent exec "colorscheme night"
    
    " guifont
    if has("win32")
        set guifont=Fixedsys\ Console:h11
    else
        set guifont=MiscFixed\ 11
    endif
    
    " Maximize window when enter vim
    if has("win32")
        au GUIEnter * simalt ~x 
    else
        " TODO: no way right now
    endif

else " if we are in terminal mode
    silent exec "colorscheme darkdot"
endif

" When editing a file, always jump to the last known cursor position.
" Don't do it when the position is invalid or when inside an event handler
" (happens when dropping a file on gvim).
autocmd BufReadPost *
\ if line("'\"") > 0 && line("'\"") <= line("$") |
\   exe "normal g`\"" |
\ endif


" Make backspace behave in a sane manner, allow backspacing over everything in insert mode.
set backspace=indent,eol,start

set autoindent 
set smartindent 

set shiftwidth=4 " set indent to 4 spaces
set tabstop=4 " set tabstop to 4 spaces
set expandtab " set expandtab on, the tab will be change to space automaticaly

set clipboard=unnamed " use clipboard register '*'(unnamed) for all y, d, c, p ops

set guioptions+=b " Present the bottom scrollbar when the longest visible line exceen the window
set guioptions-=m " disable menu 
set guioptions-=T " disable toolbar

set langmenu=none " always use English menu

set autoread " auto read same-file change 

set showmatch " show matching paren, actually shows
set matchtime=0 " 0 second to show the matching paren ( much faster )
set number " Show LineNumber
set scrolloff=0 " minimal number of screen lines to keep above and below the cursor 
set nowrap " I don't like wrap, cause in split window mode, it feel strange

set wildmenu " turn on wild menu, try typing :h and press <Tab> 
set wildignore+=*.a,*.o
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png
set wildignore+=.DS_Store,.git,.hg,.svn
set wildignore+=*~,*.swp,*.tmp

set ruler " show the cursor position all the time
set showcmd	" display incomplete commands
set showmode " display edit mode
set cmdheight=1 " 1 screen lines to use for the command-line 
set hid " allow to change buffer without saving 
set shortmess=atI " shortens messages to avoid 'press a key' prompt 
set lazyredraw " do not redraw while executing macros (much faster) 
set display+=lastline " for easy browse last line with wrap text

set showfulltag " show tag with function protype.

set hlsearch " highlight search
set incsearch " do incremental searching
set ignorecase " Set search/replace pattern to ignore case 
set smartcase " Set smartcase mode on, If there is upper case character in the search patern, the 'ignorecase' option will be override.

set history=50 " keep 50 lines of command line history
set updatetime=1000 " default = 4000
set nobackup " make no backup file and leave it around 
set noswapfile " no swap file

set statusline=[%F]%y%r%m%*%=[Line:%l/%L,Column:%c][%p%%]
set laststatus=2

set whichwrap=b,s,<,>,[,]
set formatoptions+=mB	    

" auto detect file formats
set fileformats=unix,dos,mac

set encoding=utf-8
" auto detect file encodings
lan mes zh_CN.utf-8
set fileencodings=ucs-bom,utf-8,chinese,japanese


" wean yourself off the arrow keys etc.!
noremap <unique> <Up> <nop>
noremap <unique> <Down> <nop>
noremap <unique> <Left> <nop>
noremap <unique> <Right> <nop>
noremap <unique> <Home> <nop>
noremap <unique> <End> <nop>
noremap <unique> <PageUp> <nop>
noremap <unique> <PageDown> <nop>

" moving helpful for wrap text edit
noremap <unique> k gk
noremap <unique> j gj

" win-like select all
nnoremap <unique> <leader>a ggvG$

" clear hlsearch and refresh
nnoremap <unique> <C-l> :nohlsearch<CR><C-l>

" Yanking
nnoremap Y y$

" auto close, could be overruled
inoremap ( ()<ESC>:let leavechar=")"<CR>i
inoremap [ []<ESC>:let leavechar="]"<CR>i
inoremap { {}<ESC>:let leavechar="}"<CR>i
inoremap < <><ESC>:let leavechar=">"<CR>i
inoremap " ""<ESC>:let leavechar="\""<CR>i
inoremap ' ''<ESC>:let leavechar="'"<CR>i
" get out
inoremap <unique> <C-k> <ESC>:exec "normal f" . leavechar<CR>a


func EatChar(pat)
   let c = nr2char(getchar(0))
   return (c =~ a:pat) ? '' : c
endf

