#!/bin/bash
set -euo pipefail

PARSED=$(getopt -o hn: -l help,namespace: -n "$0" -- "$@")
[ $? -ne 0 ] && exit 1
eval set -- "$PARSED"

ns=""
while true; do
    case "$1" in
        -h|--help)
			echo "kubectl pv [-n <namespace>] <resource-kind>"
			exit 0
            ;;
        -n|--namespace)
            ns="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "unexpect error"
            exit 1
            ;;
    esac
done

if [[ $# -ne 1 ]]; then
    echo "$0: resource kind is required."
    exit 1
fi

kind="$1"

if [ -n "$ns" ]; then
	ns="-n"$ns
fi

kubectl get $kind $ns -oname | fzf --preview "kubectl -oyaml $ns get {}|bat -n -l yaml --color=always" --bind ctrl-n:preview-page-down,ctrl-p:preview-page-up --preview-window=right:60%
